package org.maxgamer.quickshop.shop.hologram;

public enum DisplayAttribute {
  SMALL, SLOT,

  OFFSET_YAW, OFFSET_PITCH,

  OFFSET_X, OFFSET_Y, OFFSET_Z,

  POSE_HEAD_X, POSE_HEAD_Y, POSE_HEAD_Z,

  POSE_BODY_X, POSE_BODY_Y, POSE_BODY_Z,

  POSE_ARM_LEFT_X, POSE_ARM_LEFT_Y, POSE_ARM_LEFT_Z,

  POSE_ARM_RIGHT_X, POSE_ARM_RIGHT_Y, POSE_ARM_RIGHT_Z,

  POSE_LEG_LEFT_X, POSE_LEG_LEFT_Y, POSE_LEG_LEFT_Z,

  POSE_LEG_RIGHT_X, POSE_LEG_RIGHT_Y, POSE_LEG_RIGHT_Z;
}
